from building import *
import os

cwd = GetCurrentDir()
src = []

# 递归收集所有 .c 文件
for root, dirs, files in os.walk(cwd):
    for file in files:
        if file.endswith('.c'):
            src.append(os.path.join(root, file))

# 头文件搜索路径（根目录 + 指定的子文件夹）
subdirs = ['Peripherals', 'System', 'Misc']
CPPPATH = [cwd] + [os.path.join(cwd, d) for d in subdirs if os.path.isdir(os.path.join(cwd, d))]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')