from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd, os.path.join(cwd, '..', 'System')]

group = DefineGroup('Peripherals', src, depend=[''], CPPPATH=CPPPATH)

Return('group')
